### ISSUE TITLE
Erroneous handling of two-character ipa symbols

### ISSUE THREAD

**Issue by oserikov** [chrislit/abydos#280]
steps to reproduce:
```python3
>>> a  = "t͡ʃ"
>>> from abydos.distance import PhoneticEditDistance
>>> di = PhoneticEditDistance()
>>> di.dist(a, '')
1.0
>>> di.dist(a, 'UNK')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../abydos/distance/_phonetic_edit_distance.py", line 288, in dist
    return self.dist_abs(src, tar) / normalize_term
  File ".../abydos/distance/_phonetic_edit_distance.py", line 232, in dist_abs
    d_mat = self._alignment_matrix(src, tar, backtrace=False)
  File ".../abydos/distance/_phonetic_edit_distance.py", line 157, in _alignment_matrix
    if src[i] != tar[j]
IndexError: list index out of range
```
I believe that simply placing lengths memorization *after* `ipa_to_features` here would fix the bug, yet im not sure if the repo is still maintained so I'd better leave an issue here for others to be aware.
https://github.com/chrislit/abydos/blob/344346a5fceb6acc631b3d24e16b73a303cece2c/abydos/distance/_phonetic_edit_distance.py#L144-L148

**Comment by oserikov** [comment]
Ah sorry, the fix is already in master. Sadly, it's not in the pypi distribution
