### ISSUE TITLE
Cannot import name NINF

### ISSUE THREAD

**Issue by raffaelemancuso** [chrislit/abydos#287]
I  can't use this library:
```
>>> from abydos.distance import DiscountedLevenshtein
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[ABRIDGED]/lib/python3.12/site-packages/abydos/distance/__init__.py", line 368, in <module>
    from ._aline import ALINE
  File "[ABRIDGED]/lib/python3.12/site-packages/abydos/distance/_aline.py", line 24, in <module>
    from numpy import NINF
ImportError: cannot import name 'NINF' from 'numpy' ([ABRIDGED]/lib/python3.12/site-packages/numpy/__init__.py)
```

It looks like `NINF` was removed in numpy 2.0

**Comment by denizberkin** [comment]
Hi, I just came across to this issue. What is your installed version of abydos? If you have installed with pip or a package manager of kind, you may have ended up with versions <0.6.0, which is still there.

If you have versions below 0.6.0, I suggest cloning from most recent branch or just installing >=0.6.0.

There is also issues with the usage of np.float_ which got removed in numpy 2.0 as well. This is not fixed atm as far as I can see. So I forked and fixed it, was not much more than changing few lines to use np.float64. So if you | anyone comes across to this. You can check my fork or just change float_ usages to fix.
